### ISSUE TITLE
GC-MS Analysis Library matching - FBMN

### ISSUE THREAD

**Issue by montmasis** [CCMS-UCSD/GNPS_Workflows#567]
Hi,
I am still having problems with the GC-MS Analysis Library matching (FBMN) with data originally pre-processed in MS-DIAL.

The job works fine when I am not using the retention index library function.  When I use the retention index, I get the error (below). 

The "carbon marker" (csv) file I got as a template example from Alexander Aksenov looks like mine, beside that I have more alkanes (and I do not have C8): 
Alexander --> C8-C26
Me -->  C9-C40

Alexander thinks it could be a parsing issue and/or a missing library..

This the job that fails (below the error)
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=a7b11d597711495284a2c3c172bef2a3

Thanks in advance

Stefano

---------
Carbon_Marker_File/Carbon_Marker_File-00000.csv
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/molecularsearch-gc/release_23/calculate_kovats.py", line 69, in <module>
    main()
  File "/data/ccms-gnps/tools/molecularsearch-gc/release_23/calculate_kovats.py", line 66, in main
    args.output_library_identifications)
  File "/data/ccms-gnps/tools/molecularsearch-gc/release_23/calculate_kovats.py", line 39, in calculate_kovats
    identifications_df = pd.read_csv(input_identifications_filename, sep="\t")
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 565, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
Tool execution terminates abnormally with exit code [1]

**Comment by mwang87** [comment]
Seems your data has no identifications to the libraries. We'll have to handle that. Thanks for letting us know!

**Comment by montmasis** [comment]
Yes the identification was because I used the high-res settings suggested
for Orbitrap as in the tutorial. But Alexander said they were too narrow,
so I used 0.4 Da instead and I got 100+ hits.

The main problem now is the retention index, carbon marker. I always get an
error with that and I don't know why

**Comment by montmasis** [comment]
when I do get hits with the new settings, the carbon marker doesn´t give an
error anymore. However, I do not get any Kovats Indexes calculated in the
hits table:
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=7458f345754745be875011863b802d0b


I tried with RT reported both in minutes and seconds in the carbon marker
table
