### ISSUE TITLE
FBMN with Progenesis Data Fails

### ISSUE THREAD

**Issue by bouranij** [CCMS-UCSD/GNPS_Workflows#815]
When I attempt to run FBMN with Progenesis quantification tables I get an error that there is a missing column in the Progenesis data: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=da2cdaca1a264ef58a954146bab00ef4

I have checked my Progenesis files and there are no columns beyond the Raw Abundances, however I still get the error. I was able to get around it using this Jupyter notebook by @lfnothias : https://github.com/lfnothias/GNPS_Workflows_test_env

Looks like there may be a bug somewhere.

**Comment by lfnothias** [comment]
Hi @bouranij,

Thanks for reporting this. I will prepare a PR soon to add this support, and hopefully it will make it into a GNPS workflows release.

**Comment by fdsaraujo** [comment]
Hi colleagues,

I´m been having some problems with a job in feature-based molecular networking mode. 

MS analysis was performed under MSE mode on a Xevo G2-XS QTOF-MS system (Waters, UK) and the data were processed using PROGENESIS.

Both feature quantification table (CSV file) and MS/MS spectral summary (MSP file) were exported and uploaded to the GNPS platform, but the job returns the following error message:

Columns (1,2,3,4,5,6,7,8,13,14,15,16,17,18,19,20,21,22,23,24,25,26,32,33,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
PROGENESIS
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/reformat_quantification.py", line 135, in <module>
    main()
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/reformat_quantification.py", line 105, in main
    progenesis_formatter.convert_mgf(input_mgf, args.output_mgf, compound_scan_mapping)
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/progenesis_formatter.py", line 154, in convert_mgf
    scan = (compound_to_scan_mapping[compound_name])
KeyError: '0.40_224.0921m/z'
Tool execution terminates abnormally with exit code [1]

Can anyone help me understand what´s going on?

Thanks,

Diana Araújo

Link to the job: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=231601a13a8a4f22b268df294093770d

**Comment by fdsaraujo** [comment]
Hello collegues,

I´m been having some problems with a job in feature-based molecular networking mode. MS analysis was performed under MSE mode on a Xevo G2-XS QTOF-MS system (Waters, UK) and the data were processed using Progenesis QI.

Both feature quantification table (CSV file) and MS/MS spectral summary (MSP file) were exported and uploaded to the
GNPS platform, but the job returns the following error message:

Columns (1,2,3,4,5,6,7,8,13,14,15,16,17,18,19,20,21,22,23,24,25,26,32,33,34,35,36) have mixed types. Specify dtype option on import or set low_memory=False.
PROGENESIS
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/reformat_quantification.py", line 135, in <module>
    main()
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/reformat_quantification.py", line 105, in main
    progenesis_formatter.convert_mgf(input_mgf, args.output_mgf, compound_scan_mapping)
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/progenesis_formatter.py", line 154, in convert_mgf
    scan = (compound_to_scan_mapping[compound_name])
KeyError: '0.40_224.0921m/z'
Tool execution terminates abnormally with exit code [1]

Can anyone help me understand what´s going on?

Thanks,

Diana Araújo

Link to the job: https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=231601a13a8a4f22b268df294093770d
