### ISSUE TITLE
IIMN with OpenMS 

### ISSUE THREAD

**Issue by eeko-kon** [CCMS-UCSD/GNPS_Workflows#817]
The code is trying to insert a column called "row ID", but it already exists in the FeatureQuant table, since it is necessary for IIMN (partner assignment). 

**To Reproduce**
https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=547d8ec31e6940cd9b293f8035f2e298

**Expected behavior**
It probably shouldn't create a row ID when it already exists 

**Error**
```
[FAILED](https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=547d8ec31e6940cd9b293f8035f2e298)
[[Clone](https://gnps.ucsd.edu/ProteoSAFe/index.jsp?task=547d8ec31e6940cd9b293f8035f2e298)] [[Clone to Latest Version](https://gnps.ucsd.edu/ProteoSAFe/index.jsp?task=547d8ec31e6940cd9b293f8035f2e298&params={%22workflow%22:%22FEATURE-BASED-MOLECULAR-NETWORKING%22,%22workflow_version%22:%22current%22})][[Restart](https://gnps.ucsd.edu/ProteoSAFe/Restart?task=547d8ec31e6940cd9b293f8035f2e298)][[Delete](https://gnps.ucsd.edu/ProteoSAFe/Delete?task=547d8ec31e6940cd9b293f8035f2e298)]
OPENMS
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/reformat_quantification.py", line 135, in <module>
    main()
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/reformat_quantification.py", line 55, in main
    openms_formatter.convert_to_feature_csv(args.quantification_table, args.quantification_table_reformatted)
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/openms_formatter.py", line 63, in convert_to_feature_csv
    result.insert(0, 'row ID', result.index+1)
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/pandas/core/frame.py", line 2613, in insert
    allow_duplicates=allow_duplicates)
  File "/data/ccms-gnps/tools/anaconda3/lib/python3.5/site-packages/pandas/core/internals.py", line 4063, in insert
    raise ValueError('cannot insert {}, already exists'.format(item))
ValueError: cannot insert row ID, already exists
Tool execution terminates abnormally with exit code [1]
```

**Comment by eeko-kon** [comment]
@mwang87 no idea what happened but the link that you sent me was from an old job that's not for IIMN. Anyway, I re-ran the one above and it failed again

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=b16208305c3f4edc91721ef928e71310

**Comment by eeko-kon** [comment]
@mwang87 I ran it again with the row ID and I m getting the same error:

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=c2b619e297704d3489604eb11220f793

Without the row ID there are no nodes recognized for IIMN but it runs

https://gnps.ucsd.edu/ProteoSAFe/status.jsp?task=f8884eca19c44f819148917a41495dbf

**Comment by mwang87** [comment]
You gotta run the latest version I linked you on proteomics2.
