### ISSUE TITLE
[FBMN MZmine] Direct submission fails

### ISSUE THREAD

**Issue by robinschmid** [CCMS-UCSD/GNPS_Workflows#819]
Direct submission from MZmine to FBMN on GNPS fails with SSL exception:

@mwang87 did you change anything?

```
2022-02-25 14:57:17 WARNING io.github.mzmine.modules.io.export_features_gnps.fbmn.GnpsFbmnExportAndSubmitTask submit GNPS submit failed
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1500)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1415)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:450)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:421)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.github.mzmine.modules.io.export_features_gnps.GNPSUtils.submitFbmnJob(GNPSUtils.java:146)
	at io.github.mzmine.modules.io.export_features_gnps.GNPSUtils.submitFbmnJob(GNPSUtils.java:93)
	at io.github.mzmine.modules.io.export_features_gnps.fbmn.GnpsFbmnExportAndSubmitTask.submit(GnpsFbmnExportAndSubmitTask.java:226)
	at io.github.mzmine.modules.io.export_features_gnps.fbmn.GnpsFbmnExportAndSubmitTask.run(GnpsFbmnExportAndSubmitTask.java:189)
	at io.github.mzmine.taskcontrol.impl.WorkerThread.run(WorkerThread.java:57)
```

**Comment by mwang87** [comment]
nothing should have changed.

**Comment by robinschmid** [comment]
Just started working again
