### ISSUE TITLE
NAP_CCMS2 Error

### ISSUE THREAD

**Issue by PennyM40** [CCMS-UCSD/GNPS_Workflows#851]
NAP_CCMS2 Error

Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
Calls: load -> readChar
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'split_data/tabgnps.rda', probable reason 'No such file or directory'
Execution halted
Traceback (most recent call last):
  File "/data/beta-proteomics2/tools/nap_ccms2/merge_fragments.py", line 32, in <module>
    main()
  File "/data/beta-proteomics2/tools/nap_ccms2/merge_fragments.py", line 14, in main
    fls = os.listdir('fragmenter_res')
FileNotFoundError: [Errno 2] No such file or directory: 'fragmenter_res'
Tool execution terminates abnormally with exit code [1]

**Comment by lydia1201** [comment]
Hi I have the same issue. Could anyone help to solve this problem? 
http://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=ae27cc7176e04dd5ab1c4a01a12a48ba

![Uploading 3680453E-F66B-4CB9-8EE4-7E3A1C1354B2.png…]()

**Comment by ridasilva** [comment]
Hello,

Please, post questions with taskids here
https://groups.google.com/g/molecular_networking_bug_reports

@PennyM40 I need your taskid or job link.

@lydia1201 avoid using the old snets workflow, user snets-V2, I was able to change an import in the tool and run your job
https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=8641aef95c8644a59c8f305fe51c9cb0

Cheers,
Ricardo

**Comment by lydia1201** [comment]
> Hello,
> 
> Please, post questions with taskids here https://groups.google.com/g/molecular_networking_bug_reports
> 
> @PennyM40 I need your taskid or job link.
> 
> @lydia1201 avoid using the old snets workflow, user snets-V2, I was able to change an import in the tool and run your job https://proteomics2.ucsd.edu/ProteoSAFe/status.jsp?task=8641aef95c8644a59c8f305fe51c9cb0
> 
> Cheers, Ricardo

Hi Ricardo,

Yes, I tried, It worked. Thank you very much for solving the problem.

Cheers

Lydia

**Comment by PennyM40** [comment]
Hello,I am actually sorted now I realised that it was my pre-processing that was not right in MZmine (MS1 and MS2) pairing. I managed to run the job once I pre-processed carefully.

Thanks



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by MuyaoXi9271** [comment]
Hi all,

I also meet the same error. I preprocess the data by using XCMS and run FBMN (7b85647fe2a4446dbcc52549d8f28dce), then I continue to run NAP (31dea4f0d098449496c6844a7ab098e5) by typing the id of FBMN. 

Could you please share the solution to solve this error, I appreciate it a lot.

Best,
Muyao

**Comment by BioGavin** [comment]
I encountered the same issue. After some research, I found two possible solutions online. It turns out I imported the FBMN data but mistakenly chose the wrong workflow type. Once I switched to MZmine, the problem was resolved.

- [Error in NAP workflow](https://groups.google.com/g/molecular_networking_bug_reports/c/I2a2UX9_8wY)

- [Error message in performing NAP](https://groups.google.com/g/molecular_networking_bug_reports/c/seazBPvWmdA)
