### ISSUE TITLE
GNPS FBMN issue

### ISSUE THREAD

**Issue by lzlmby** [CCMS-UCSD/GNPS_Workflows#872]
I have been running MSDIAL based FBMN analysis. My data is from Thermo Orbitrap. I always get this error:

Columns (0,1,2,6,7,8,9,10,11,12,13,14,15,16,17,18,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
MSDIAL
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/reformat_quantification.py", line 135, in <module>
    main()
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/reformat_quantification.py", line 75, in main
    msdial_formatter.convert_to_feature_csv(args.quantification_table, args.quantification_table_reformatted)
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/msdial_formatter.py", line 27, in convert_to_feature_csv
    scan = record["Alignment ID"]
KeyError: 'Alignment ID'
Tool execution terminates abnormally with exit code [1]

**Comment by lfnothias** [comment]
Hi, I believe this is related to the MSDIAL ver 5. Please check out this for a work around (either using ver 4 or the notebook) https://groups.google.com/u/0/g/molecular_networking_bug_reports/c/pyQ_rU5g7ps
