### ISSUE TITLE
Connection issues ProteoSAFe

### ISSUE THREAD

**Issue by JosuaCarl** [CCMS-UCSD/GNPS_Workflows#882]
**Describe the bug**
All jobs I run end with OpenSSL complaining over a failed handshake.

**To Reproduce**
Steps/Task to reproduce the behavior:
1. Go to '[Feature Based Networking](https://gnps-quickstart.ucsd.edu/featurebasednetworking)'
2. Pass feature-table and MS2 spectra

**Expected behavior**
For the job to finish without an error.

**Error-Message**
```
Traceback (most recent call last):
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 453, in wrap_socket
    cnx.do_handshake()
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 344, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 459, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='gnps.ucsd.edu', port=443): Max retries exceeded with url: /ProteoSAFe/result_json.jsp?task=698fc5a09db74c7492983b3673ff5bf6&view=molecule_explorer_v2_summary&show=true (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/getGNPS_library_annotations.py", line 219, in <module>
    main()
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/getGNPS_library_annotations.py", line 216, in main
    enrich_output(input_result_filename, output_result_filename, topk=args.topk)
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/getGNPS_library_annotations.py", line 15, in enrich_output
    molecule_explorer_df = pd.DataFrame(ming_gnps_library.get_molecule_explorer_dataset_data())
  File "/data/ccms-gnps/tools/feature-based-molecular-networking/release_28.2/scripts/ming_gnps_library.py", line 190, in get_molecule_explorer_dataset_data
    r = requests.get(url)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/data/ccms-gnps/tools/miniconda3_gamma/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='gnps.ucsd.edu', port=443): Max retries exceeded with url: /ProteoSAFe/result_json.jsp?task=698fc5a09db74c7492983b3673ff5bf6&view=molecule_explorer_v2_summary&show=true (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
Tool execution terminates abnormally with exit code [1]
```

**Additional context**
The URL [https://gnps.ucsd.edu/ProteoSAFe/result_json.jsp?task=698fc5a09db74c7492983b3673ff5bf6&view=molecule_explorer_v2_summary&show=true](https://gnps.ucsd.edu/ProteoSAFe/result_json.jsp?task=698fc5a09db74c7492983b3673ff5bf6&view=molecule_explorer_v2_summary&show=true) provides a json, as expected.

**Comment by JosuaCarl** [comment]
The initial error did not appear again after a day passed. Rather I now get:
```
There was an error submitting this workflow task to the ProteoSAFe workflow engine.
Please contact ccms@proteomics.ucsd.edu for more information.
```
As there seems to be some issue with ProteoSAFe, I will contact the mail above as instructed, but I guess I'm gonna reach the same people here.

**Comment by JosuaCarl** [comment]
I don't know why, but now everything ran smoothly. I'm gonna close this up now. Hopefully I was the only one affected.

Edit: I know why now, thanks to a reply by ProteoSAFe. The server had a problem which backed up a lot of jobs, causing the fails.
